version: '3.9'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  nextjs:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DB_PORT=5432
    links:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app.next
volumes:
  db:
    driver: local
